name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: app_user
          POSTGRES_PASSWORD: app_password
          POSTGRES_DB: task_management
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U app_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install and Test Backend
      working-directory: ./backend
      run: |
        npm install
        npm run build
        npm test

    - name: Install and Test Frontend
      working-directory: ./frontend
      run: |
        npm install
        npm run build
        npm test